window.FULL_MTG_CATALOG = [
  "Vraska, Soul of Stone", "Vraska, the Cutting Glare", "Brotherhood's End", "The Endstone", "Desolation Twin",
  "Writhing Chrysalis", "Catacomb Sifter", "Bane of Bala Ged", "Myrkul, Lord of Bones", "Slimefoot, the Stowaway",
  "Frodo, Adventurous Hobbit", "Sam, Loyal Attendant", "Oroku Saki, Shredder Rising", "Splinter, Hamato Yoshi",
  "Michelangelo, Game Master", "April O'Neil, Kunoichi Trainer", "Jennika, Bad Apple Big Sister", "Dreadfeast Demon",
  "Overseer of the Damned", "Pestilence Demon", "Demon of Catastrophes", "Desecration Demon", "Demon of Loathing",
  "Mindwrack Demon", "Rakshasa Debaser", "Lorcan, Warlock Collector", "Crabomination", "Taborax, Hope's Demise",
  "Eater of Hope", "Thraxodemon", "Arcane Signet", "Chromatic Lantern", "Talisman of Impulse", "Hedron Archive",
  "Mind Stone", "Reckoner Bankbuster", "Mirage Mirror", "Sting, Bilbo's Sword", "Silver Surfer, Galactus's Herald",
  "Genesis Hydra", "Forgotten Ancient", "Sunblast Angel", "The Vision", "Thranduil, Sindarin Liege",
  "Bilbo Baggins, Burglar", "Beorn, Reluctant Host", "Tom, Bert, and William", "Galion, Elvenking's Butler",
  "Bombur, Gentle Dreamer", "Gollum the Abandoned", "Azog, Moria's Ruin", "Wood Elves", "Thrór's Map",
  "Through the Forest Gate", "Mirkwood", "Bolg of the North", "Dori, Bearer of Friends", "Gandalf, Spark Starter",
  "Gollum, Silent Slinker", "Bilbo's Deadly Slice", "Gnashing of Teeth", "Gathering of Darkness", "Goblin-town",
  "Tidings of War", "Rage Into the Valley", "Doom Foretold", "Gleeful Sabotage", "Summon: Fenrir", "Syphon Essence",
  "Mechan Shieldmate", "Firja's Retribution", "Vivien's Talent", "Animist's Awakening", "Glimmerburst",
  "Walk with the Ancestors", "Plasma Bolt", "Intrepid Tenderfoot", "Verdant Mastery", "Ruthless Waterbender",
  "Molecular Modifier", "Meltsrider Eulogist", "Illvoi Operative", "Taster of Wares", "Flight-Deck Coordinator",
  "Far Traveler", "Illvoi Infiltrator", "Tameshi, Reality Architect", "Tryo, Diamondblade Mage", "Arni, Humble Scribe",
  "Gallia, Tragic Host", "Uldaros Theorix", "Way of the Deathbringer", "Rise of the Deathbringer", "Countersculpt",
  "Extended Absence", "Theorix Charm", "Sphinx's Approach", "Pia, Determined Rebuilder", "Pia, Aether Ascetic",
  "Saheeli, Consul of Oversight", "Loot, the Nexus", "Winter, Team Player", "Tetsuko Umezawa, Pursuer",
  "Arni, Renowned Champion", "Teyo, Lightshield Expert", "Koth, the Geomancer", "Kindred Judgment", "Fatehold Charm",
  "Wrath of the Bloodmane", "Meticulous Commons", "Slingerquill Annex", "Vigorbloom Annex", "Saheeli, Jewel of Avishkar",
  "Xorn of the Homestead", "Soul Salvage", "Erstwhile Trooper", "Ferocity of the Wild", "Mishra's Kirin",
  "Compel Brutality", "Tethermage's Advantage", "No Admittance", "Campus Crier", "Prudent Fateseer", "Inspired Tethermage",
  "Fulminous Forte", "Cruel Calculations", "Carnivorous Cultivator", "Flourishing Grapple", "Fatehold Chronologist",
  "Fateshaper Aspirant", "Sureshor Sower", "Something Worth Saving", "Artificer's Acumen", "Guiding Hydra",
  "Dreadflight Monstrosity", "Restore with Empathy", "Graft Surgeon", "Shattering Pegasus", "Arcane Amphisbaena",
  "Heartstring Puller", "Konstruri Improviser", "Vindicate's Triumph", "Surgical Precision", "Hexhaven Battalion",
  "Giltclaw Crusher", "Mind Murderer", "Vindictive Warden", "Giant Growth", "Moldgraf Scavenger", "Greater Sandwurm",
  "Stitched Mangler", "Ritual of Rejuvenation", "Martyr of Dusk", "Kessig Dire Strain", "Scrapsail Skaab", "Forge Devil",
  "Gatekeeper Vine", "Tackle Artist", "Roaring Embermare", "Zealous Tormentor", "Swamp", "Forest", "Plains", "Mountain", "Island"
];
