window.FULL_MTG_CATALOG = [
  // PART 1: COMMANDERS, MYTHICS, RARE CREATURES & DEVOID ELDRAZI
  "Myrkul, Lord of Bones", "Slimefoot, the Stowaway", "Frodo, Adventurous Hobbit", "Sam, Loyal Attendant",
  "Oroku Saki, Shredder Rising", "Splinter, Hamato Yoshi", "Michelangelo, Game Master", "April O'Neil, Kunoichi Trainer",
  "Jennika, Bad Apple Big Sister", "Vraska, Soul of Stone", "Vraska, the Cutting Glare", "Pia, Determined Rebuilder",
  "Pia, Aether Ascetic", "Saheeli, Consul of Oversight", "Loot, the Nexus", "Winter, Team Player",
  "Tetsuko Umezawa, Pursuer", "Arni, Renowned Champion", "Teyo, Lightshield Expert", "Koth, the Geomancer",
  "Thranduil, Sindarin Liege", "Bilbo Baggins, Burglar", "Beorn, Reluctant Host", "Tom, Bert, and William",
  "Galion, Elvenking's Butler", "Bombur, Gentle Dreamer", "Gollum the Abandoned", "Azog, Moria's Ruin",
  "Bolg of the North", "Dori, Bearer of Friends", "Gandalf, Spark Starter", "Gollum, Silent Slinker",
  "Lorcan, Warlock Collector", "Taborax, Hope's Demise", "Dreadfeast Demon", "Overseer of the Damned",
  "Pestilence Demon", "Demon of Catastrophes", "Desecration Demon", "Demon of Loathing", "Mindwrack Demon",
  "Rakshasa Debaser", "Crabomination", "Eater of Hope", "Thraxodemon", "Desolation Twin",
  "Writhing Chrysalis", "Catacomb Sifter", "Bane of Bala Ged", "Silver Surfer, Galactus's Herald",
  "Genesis Hydra", "Forgotten Ancient", "Sunblast Angel", "The Vision", "Migloz, Maze Crusher",
  "Gallia, Tragic Host", "Tameshi, Reality Architect", "Tryo, Diamondblade Mage", "Arni, Humble Scribe",
  "Saheeli, Jewel of Avishkar", "Xorn of the Homestead",
    // PART 2: INSTANTS, SORCERIES, ARTIFACTS & NON-BASIC LANDS
  "Brotherhood's End", "The Endstone", "Kindred Judgment", "Fatehold Charm", "Wrath of the Bloodmane",
  "Pillage the Bog", "Bilbo's Deadly Slice", "Gnashing of Teeth", "Gathering of Darkness", "Tidings of War",
  "Rage Into the Valley", "Doom Foretold", "Gleeful Sabotage", "Summon: Fenrir", "Syphon Essence",
  "Firja's Retribution", "Vivien's Talent", "Animist's Awakening", "Glimmerburst", "Walk with the Ancestors",
  "Plasma Bolt", "Surgical Precision", "Compel Brutality", "Tethermage's Advantage", "No Admittance",
  "Fulminous Forte", "Cruel Calculations", "Flourishing Grapple", "Something Worth Saving", "Artificer's Acumen",
  "Restore with Empathy", "Vindicate's Triumph", "Giant Growth", "Ritual of Rejuvenation", "Soul Salvage",
  "Countersculpt", "Extended Absence", "Theorix Charm", "Sphinx's Approach", "Arcane Signet",
  "Chromatic Lantern", "Talisman of Impulse", "Hedron Archive", "Mind Stone", "Reckoner Bankbuster",
  "Mirage Mirror", "Sting, Bilbo's Sword", "Thrór's Map", "Mirkwood", "Through the Forest Gate",
  "Ferocity of the Wild", "Mishra's Kirin", "Meticulous Commons", "Slingerquill Annex", "Vigorbloom Annex",
  "Goblin-town",
    // PART 3: COMMON/UNCOMMON CREATURES, UTILITY ENGINES & LANDS
  "Thallid Devourer", "Sporecrown Thallid", "Deathbloom Thallid", "Tukatongue Thallid", "Undercellar Myconid",
  "Yavimaya Sapherd", "Bloodthrone Vampire", "Bloodflow Connoisseur", "Acolyte of Aclazotz", "Emrakul's Evangel",
  "Intrepid Tenderfoot", "Verdant Mastery", "Ruthless Waterbender", "Molecular Modifier", "Meltsrider Eulogist",
  "Illvoi Operative", "Taster of Wares", "Flight-Deck Coordinator", "Far Traveler", "Illvoi Infiltrator",
  "Uldaros Theorix", "Way of the Deathbringer", "Rise of the Deathbringer", "Mechan Shieldmate", "Campus Crier",
  "Prudent Fateseer", "Inspired Tethermage", "Carnivorous Cultivator", "Fatehold Chronologist", "Fateshaper Aspirant",
  "Sureshor Sower", "Guiding Hydra", "Dreadflight Monstrosity", "Graft Surgeon", "Shattering Pegasus",
  "Arcane Amphisbaena", "Heartstring Puller", "Konstruri Improviser", "Hexhaven Battalion", "Giltclaw Crusher",
  "Mind Murderer", "Vindictive Warden", "Moldgraf Scavenger", "Greater Sandwurm", "Stitched Mangler",
  "Martyr of Dusk", "Kessig Dire Strain", "Scrapsail Skaab", "Forge Devil", "Gatekeeper Vine",
  "Tackle Artist", "Roaring Embermare", "Zealous Tormentor", "Erstwhile Trooper", "Wood Elves",
  "Swamp", "Forest", "Plains", "Mountain", "Island"
];
