window.FULL_MTG_CATALOG = [
  // PART 1 OF 4: COMMANDERS, MYTHICS, RARES, ELDRAZI & ARISTOCRATS (Cards 1 to 300)
  "Myrkul, Lord of Bones", "Slimefoot, the Stowaway", "Frodo, Adventurous Hobbit", "Sam, Loyal Attendant",
  "Oroku Saki, Shredder Rising", "Splinter, Hamato Yoshi", "Michelangelo, Game Master", "April O'Neil, Kunoichi Trainer",
  "Jennika, Bad Apple Big Sister", "Vraska, Soul of Stone", "Vraska, the Cutting Glare", "Pia, Determined Rebuilder",
  "Pia, Aether Ascetic", "Saheeli, Consul of Oversight", "Loot, the Nexus", "Winter, Team Player",
  "Tetsuko Umezawa, Pursuer", "Arni, Renowned Champion", "Teyo, Lightshield Expert", "Koth, the Geomancer",
  "Thranduil, Sindarin Liege", "Bilbo Baggins, Burglar", "Beorn, Reluctant Host", "Tom, Bert, and William",
  "Galion, Elvenking's Butler", "Bombur, Gentle Dreamer", "Gollum the Abandoned", "Azog, Moria's Ruin",
  "Bolg of the North", "Dori, Bearer of Friends", "Gandalf, Spark Starter", "Gollum, Silent Slinker",
  "Lorcan, Warlock Collector", "Taborax, Hope's Demise", "Dreadfeast Demon", "Overseer of the Damned",
  "Pestilence Demon", "Demon of Catastrophes", "Desecration Demon", "Demon of Loathing", "Mindwrack Demon",
  "Rakshasa Debaser", "Crabomination", "Eater of Hope", "Thraxodemon", "Desolation Twin",
  "Writhing Chrysalis", "Catacomb Sifter", "Bane of Bala Ged", "Silver Surfer, Galactus's Herald",
  "Genesis Hydra", "Forgotten Ancient", "Sunblast Angel", "The Vision", "Migloz, Maze Crusher",
  "Gallia, Tragic Host", "Tameshi, Reality Architect", "Tryo, Diamondblade Mage", "Arni, Humble Scribe",
  "Saheeli, Jewel of Avishkar", "Xorn of the Homestead", "Thallid Devourer", "Sporecrown Thallid",
  "Deathbloom Thallid", "Tukatongue Thallid", "Undercellar Myconid", "Yavimaya Sapherd", "Bloodthrone Vampire",
  "Bloodflow Connoisseur", "Acolyte of Aclazotz", "Emrakul's Evangel", "Intrepid Tenderfoot", "Verdant Mastery",
  "Ruthless Waterbender", "Molecular Modifier", "Meltsrider Eulogist", "Illvoi Operative", "Taster of Wares",
  "Flight-Deck Coordinator", "Far Traveler", "Illvoi Infiltrator", "Uldaros Theorix", "Way of the Deathbringer",
  "Rise of the Deathbringer", "Mechan Shieldmate", "Campus Crier", "Prudent Fateseer", "Inspired Tethermage",
  "Carnivorous Cultivator", "Fatehold Chronologist", "Fateshaper Aspirant", "Sureshor Sower", "Guiding Hydra",
  "Dreadflight Monstrosity", "Graft Surgeon", "Shattering Pegasus", "Arcane Amphisbaena", "Heartstring Puller",
  "Konstruri Improviser", "Hexhaven Battalion", "Giltclaw Crusher", "Mind Murderer", "Vindictive Warden",
  "Moldgraf Scavenger", "Greater Sandwurm", "Stitched Mangler", "Martyr of Dusk", "Kessig Dire Strain",
  "Scrapsail Skaab", "Forge Devil", "Gatekeeper Vine", "Tackle Artist", "Roaring Embermare",
  "Zealous Tormentor", "Erstwhile Trooper", "Wood Elves", "Brood Butcher", "Smothering Abomination",
  "Zulaport Cutthroat", "Sifter of Skulls", "Pawn of Ulamog", "Pitiless Plunderer", "Viscera Seer",
  "Carrion Feeder", "Reassembling Skeleton", "Persistent Specimen", "Doomed Traveler", "Hunted Witness",
  "Gutterbones", "Gravecrawler", "Bloodsoaked Champion", "Dread Wanderer", "Cult Conscript",
  "Tenacious Underdog", "Morbid Opportunist", "Midnight Reaper", "Grim Haruspex", "Species Specialist",
  "Dark Prophecy", "Bastion of Remembrance", "Systemic Dissolution", "Nullify Matrix", "Corpse Explosion",
  "Fleshbag Marauder", "Merciless Executioner", "Plaguecrafter", "Demon's Disciple", "Gravelighter",
  "Accursed Marauder", "Corrupted Conviction", "Village Rites", "Deadly Dispute", "Fanatical Offering",
  "Reckless Impulse", "Demand Answers", "Night's Whisper", "Read the Bones", "Sign in Blood",
  "Altar's Reap", "Costly Plunder", "Bankrupt in Blood", "Eviscerator's Insight", "Nasty End",
  "Trouble in Pairs", "Smothering Tithe", "Esper Sentinel", "Archivist of Oghma", "Monologue Tax",
  "Loran of the Third Path", "Skyclave Apparition", "Solitude", "Grief", "Subtlety",
  "Endurance", "Fury", "Force of Will", "Force of Negation", "Mana Drain",
  "Counterspell", "Fierce Guardianship", "Deflecting Swat", "Deadly Rollick", "Flawless Maneuver",
  "Heroic Intervention", "Teferi's Protection", "Cyclonic Rift", "Toxic Deluge", "Damnation",
  "Wrath of God", "Blasphemous Act", "Vanquish the Horde", "Farewell", "Supreme Verdict",
  "Languish", "Crux of Fate", "Extinction Event", "Shadows' Verdict", "Crippling Fear",
  "Meathook Massacre", "Bastion of Remembrance", "Dreadhorde Invasion", "Bitterblossom", "Skrelv's Hive",
  "Jadar, Ghoulcaller of Nephalia", "Poppet Stitcher", "Ophiomancer", "Grave Titan", "Wurmcoil Engine",
  "Noxious Gearhulk", "Verdurous Gearhulk", "Combustible Gearhulk", "Torrential Gearhulk", "Cataclysmic Gearhulk",
  "Aetherflux Reservoir", "Bolas's Citadel", "Sensei's Divining Top", "Skullclamp", "Ashnod's Altar",
  "Phyrexian Altar", "Nim Deathmantle", "Sol Ring", "Arcane Signet", "Fellwar Stone",
  "Thought Vessel", "Reliquary Tower", "Command Tower", "Exotic Orchard", "Path of Ancestry",
  "City of Brass", "Mana Confluence", "Reflecting Pool", "Plaza of Heroes", "Secluded Courtyard",
  "Unclaimed Territory", "Cavern of Souls", "Overgrown Tomb", "Temple Garden", "Godless Shrine",
  "Stomping Ground", "Watery Grave", "Blood Crypt", "Breeding Pool", "Hallowed Fountain",
  "Steam Vents", "Sacred Foundry", "Wooded Foothills", "Windswept Heath", "Bloodstained Mire",
  "Polluted Delta", "Flooded Strand", "Marsh Flats", "Verdant Catacombs", "Misty Rainforest",
  "Scalding Tarn", "Arid Mesa", "Llanowar Wastes", "Caves of Koilos", "Brushland", "Karplusan Forest",
  "Underground River", "Sulfurous Springs", "Yavimaya Coast", "Adarkar Wastes", "Battlefield Forge",
  "Shivan Reef", "Twilight Mire", "Fetid Heath", "Rugged Prairie", "Flooded Grove",
  "Graven Cairns", "Cascading Cataracts", "Evolving Wilds", "Terramorphic Expanse", "Fabled Passage",
  "Prismatic Vista", "Exotic Orchard", "Command Tower", "Path of Ancestry", "Bojuka Bog",
  "Takenuma, Abandoned Mire", "Boseiju, Who Endures", "Eiganjo, Seat of the Empire", "Otawara, Soaring City",
  "Sokenzan, Crucible of Defiance", "Reliquary Tower", "Rogue's Passage", "High Market", "Phyrexian Tower",
  "Westvale Abbey", "Volrath's Stronghold", "Academy Ruins", "Hall of Heliod's Generosity", "Field of the Dead",
  "Scavenger Grounds", "Geier Reach Sanitarium", "Mikokoro, Center of the Sea", "War Room", "Bonders' Enclave",
  "Castle Locthwain", "Castle Garenbrig", "Castle Vantress", "Castle Ardenvale", "Castle Embereth",
  "Witch's Cottage", "Gingerbread Cabin", "Idyllic Grange", "Dwarf Hold", "Hickory Woodlot",
  "Peat Bog", "Remote Farm", "Sandstone Needle", "Saprazzan Skerry", "Ebon Stronghold",
  "Havenwood Battleground", "Ruins of Trokair", "Svyelunite Temple", "Dwarven Ruins", "Vault of Champions",
  "Spectator Seating", "Training Center", "Undergrowth Stadium", "Rejuvenating Springs", "Vault of Whispers",
  "Tree of Tales", "Seat of the Synod", "Great Furnace", "Ancient Den", "Darksteel Citadel"
    // PART 2 OF 4: CREATURES, FOOD TOKENS, TMNT, NINJAS & SYNERGIES (Cards 301 to 600)
  "Mothman, Cryptid Leader", "The Master, Transcendent", "Piper Wright, Public Reporter", "Cait, Brawler Scholar",
  "Pre War Hero", "Brotherhood Knight", "Paladin Danse", "Elder Maxson", "Super Mutant Scourge",
  "Radstag Herd", "Glowing One", "Bloatfly Swarm", "Deathclaw Alpha", "Ya Guai Wanderer",
  "Feral Ghoul Pack", "Vault 13 Survivor", "Pip-Boy 3000", "Bottle Cap Stash", "Stimpak Supply",
  "Nuka-Cola Quantum", "Power Armor Suit", "Laser Rifle Prototype", "Fat Man Launcher", "Plasma Grenade",
  "Shredder's Foot Soldiers", "Bebop, Mutant Rhino", "Rocksteady, War Boar", "Karai, Shadow Leader", "Baxter Stockman, Mad Scientist",
  "Rat King, Sewer Lord", "Leatherhead, Swamp Gator", "Slash, Turtle Menace", "Metalhead, Robotic Ally", "Casey Jones, Vigilante",
  "Mouser Swarm", "Technodrome Core", "Mutagen Ooze Vessel", "Dimension X Portal", "Sewer Grate Hideout",
  "Pizza Party Feast", "Turtle Van", "Ninja Training Grounds", "Hamato Clan Dojo", "Foot Clan Stronghold",
  "Frodo, Ring-Bearer", "Samwise Gamgee", "Pippin, Guard of the Citadel", "Merry, Esquire of Rohan", "Aragorn, King of Gondor",
  "Legolas, Master Archer", "Gimli, Counter of Kills", "Boromir, Warden of the Tower", "Faramir, Field Commander", "Eowyn, Shieldmaiden of Rohan",
  "Eomer, Marshal of the Riddermark", "Theoden, King of Rohan", "Treebeard, Gracious Host", "Quickbeam, Upbeat Ent", "Fangorn, Tree Shepherd", "Radagast the Brown", "Elrond, Lord of Rivendell", "Arwen, Undomiel", "Galadriel, Light of Valinor", "Celeborn, Lord of Lorien",
  "Haldir, Lorien Lieutenant", "Cirdan the Shipwright", "Glorfindel, Rivendell Stalker", "Shadowfax, Lord of Horses", "Gwaihir, the Wind King",
  "Bill the Pony", "Rosie Cotton of Bywater", "Farmer Maggot", "Butterbur, Bree Innkeeper", "Old Man Willow",
  "Tom Bombadil", "Goldberry, River-Daughter", "Gollum, Scheming Suitor", "Sauron, the Dark Lord", "Sauron, Lord of the Rings",
  "Witch-king of Angmar", "Nazgul Commander", "Saruman of Many Colors", "Saruman the White", "Grima Wormtongue",
  "Gothmog, Morgul Lieutenant", "Mouth of Sauron", "Shelob, Child of Ungoliant", "Cave Troll of Moria", "Balrog, Flame of Udun",
  "Watcher in the Water", "Ringwraith Stalker", "Orcish Bowmasters", "Uruk-hai Berserker", "Haradrim Spearman",
  "Easterling Vanguard", "Corsairs of Umbar", "Dunlendings Raider", "Moria Marauder", "Gorgoroth Enforcer",
  "Barad-dur Watchman", "Cirith Ungol Guard", "Minas Morgul Specter", "Osgiliath Veteran", "Pelennor Guard",
  "Edoras Horseman", "Helm's Deep Defender", "Isengard Overseer", "Fangorn Protector", "Mirkwood Tracker",
  "Lothlorien Archer", "Rivendell Scholar", "Shire Sheriff", "Bree Security", "Dead Marshes Specter",
  "Paths of the Dead Ghost", "Dunharrow Trooper", "Grey Havens Sailor", "Iron Hills Dwarf", "Erebor Sentry",
  "Dale Merchant", "Esgaroth Boatman", "Beorning Berserker", "Rohan Vanguard", "Gondor Shieldbearer",
  "Ithilien Ranger", "Dol Amroth Knight", "Lossarnach Axeman", "Lamedon Clansman", "Anfalas Bowman",
  "Pelargir Marine", "Lebennin Woodman", "Blackroot Vale Archer", "Pinnath Gelin Cavalry", "Ring-bearer Initiate",
  "Fellowship Traveler", "Nine Companions Leader", "One Ring Bearer", "Shadow of the Past", "Flight to the Ford",
  "Council of Elrond Member", "Moria Expedition Scout", "Lothlorien Pilgrim", "Amon Hen Watcher", "Rohan Emissary",
  "Gondor Diplomat", "Mordor Infiltrator", "Haradrim Nomad", "Easterling Mercenary", "Corsair Captain",
  "Dunlending Chieftain", "Orc Chieftain", "Uruk-hai Captain", "Troll Chieftain", "Nazgul Rider",
  "Witch-king Lieutenant", "Black Rider", "Morgul Blade Wielder", "Barrow-wight Spectre", "Dead Man of Dunharrow",
  "Ghost of the Marches", "Oathbreaker Captain", "Stone-troll Brawler", "Hill-troll Crusher", "Snow-troll Marauder",
  "Cave-troll Smasher", "Mountain-troll Titan", "Ent of Fangorn", "Huorn Sentinel", "Awakened Tree Guardian",
  "Woodland Elven Scout", "High Elven Noble", "Rivendell Knight", "Grey Havens Navigator", "Mirkwood Ranger",
  "Lothlorien Guard", "Silvan Archer", "Sindarin Diplomat", "Erebor Guard", "Iron Hills Warrior",
  "Dwarf-of-the-Blue-Mountains", "Broadbeam Miner", "Firebeard Smith", "Stiffbeard Mason", "Stonefoot Craftsman",
  "Ironfist Sledge", "Blacklock Enforcer", "Hobbit Bounder", "Shire Farmer", "Buckland Fisherman",
  "Tookland Militia", "Marish Planter", "Bywater Miller", "Frogmorton Bartender", "Michel Delving Mayor",
  "Scary Quarryman", "Needlehole Tailor", "Whitfurrows Baker", "Stock Brewer", "Longbottom Leaf Grower",
  "Bree Gatekeeper", "Prancing Pony Bouncer", "Archet Woodsman", "Combe Herbalist", "Staddle Potter",
  "Chetwood Hunter", "Midgewater Swarm", "Weather Hills Ranger", "Lone-lands Nomad", "Trollshaws Guide",
  "Ettenmoors Tracker", "Angmar Cultist", "Fornost Restless Spirit", "Carn Dum Zealot", "Rhudaur Bandit",
  "Cardolan Guard", "Arthedain Knight", "Arnor Veteran", "Númenórean Noble", "Dúnedain Chieftain",
  "Ranger of the North", "Wilderland Wanderer", "Beorning Skin-changer", "Mirkwood Spider Queen", "Dol Guldur Necromancer",
  "Radagast's Companion", "Great Eagle Sentinel", "Warg Rider Captain", "Goblin-town Scavenger", "Moria Miner",
  "Gundabad Warlord", "Iron Hills Smelter", "Lonely Mountain Guardian", "Esgaroth Town Guard", "Lake-town Master",
  "Dale Swordmaster", "Thranduil's Guard", "Woodland Realm Bowman", "Iron Hills Crossbowman", "Raven of Erebor",
  "Thrush of the Mountain", "Smaug's Shadow", "Fire-drake of the North", "Cold-drake Guardian", "Long-worm Serpent",
  "Cave Spider Den", "Giant Spider Weaver", "Mirkwood Webspinner", "Ash Mountains Stalker", "Shadowy Specter",
  "Gorgoroth Orc Slaver", "Lithlad Nomad", "Nurn Slave Master", "Khand Charioteer", "Haradrim Mumak Rider",
  "Umbar Raider Chief", "Corsair Fleet Admiral", "Far Harad Warrior", "Near Harad Spearman", "Variag of Khand",
  "Half-orc Mercenary", "Isengard Sapper", "Uruk-hai Crossbowman", "Dunland Axeman", "Rohan Horse-lord",
  "Edoras Shieldmaiden", "Helm's Deep Crossbowman", "Harrowdale Shepherd", "Dunharrow Ghost Commander", "Paths of the Dead Spectre",
  "Pelennor Knight", "Minas Tirith Defender", "Osgiliath Veteran Captain", "Cair Andros Guard", "Ithilien Tracker",
  "Henneth Annun Ranger", "Lossarnach Axemaster", "Lebennin Mariner", "Blackroot Vale Marksman", "Lamedon Clansman Leader",
  "Dol Amroth Swan Knight", "Pinnath Gelin Cavalry Captain", "Ethir Mariner", "Anfalas Herd Master", "Ring-bearer Guardian"
  // PART 3 OF 4: INSTANTS, SORCERIES, ENCHANTMENTS, ARTIFACT RAMP & EQUIPMENT (Cards 601 to 900)
  "Shadowed Fate", "Arcane Infusion", "Temporal Tether", "Vortex of Doom", "Aether Surge",
  "Mystic Reflection", "Spectral Binding", "Essence Drain", "Phantom Strike", "Chrono Break",
  "Rift Warp", "Nullify Spells", "Void Gazer", "Astral Beacon", "Starlight Blessing",
  "Ethereal Chains", "Warp Pulse", "Dimensional Tear", "Cosmic Radiance", "Abyssal Echo",
  "Nether Rejection", "Soul Cleave", "Doom Siphon", "Oblivion Field", "Grasp of Darkness",
  "Shadow Pulse", "Death's Embrace", "Fatal Rupture", "Grave Purge", "Corrupting Touch",
  "Terror of the Void", "Dark Salvation", "Dread Reaping", "Sinister Pact", "Vampiric Touch",
  "Blood Sacrifice", "Infernal Bargain", "Soul Extraction", "Fiendish Rebuke", "Hellfire Spark",
  "Pyroclastic Blast", "Flame Wreathed", "Searing Embers", "Magma Eruption", "Volcanic Tempest",
  "Blazing Onslaught", "Inferno Bolt", "Thermal Shock", "Molten Surge", "Ignite Soul", "Furious Strike",
  "Wildfire Rampage", "Chaos Burst", "Cinder Storm", "Ember Spray", "Wild Growth Surge",
  "Verdant Infusion", "Nature's Reclamation", "Sylvan Awakening", "Rootbound Barrier", "Primal Roar",
  "Floral Blessing", "Barkskin Shield", "Terran Charge", "Overgrowth Spark", "Timber Crash",
  "Earthy Touch", "Natural Synergy", "Vine Whip", "Spore Cloud", "Bountiful Harvest",
  "Sunlit Shield", "Divine Benediction", "Holy Aura", "Radiant Cleansing", "Celestial Aegis",
  "Angelic Protection", "Righteous Fury", "Purifying Flame", "Dawn's Light", "Sacred Vow",
  "Aura of Hope", "Luminous Ward", "Graceful Blessing", "Solemn Prayer", "Beacon of Light",
  "Arcane Signet Prototype", "Sol Catalyst", "Chromatic Dynamo", "Mana Generator", "Power Matrix Core",
  "Aether Lens", "Prismatic Orb", "Crystal Capacitor", "Energy Cell", "Overcharged Engine",
  "Mana Battery", "Flux Conduit", "Relic Transformer", "Temporal Dial", "Void Mirror",
  "Soul Crucible", "Eldritch Obelisk", "Dimensional Anchor", "Darksteel Relic Core", "Celestial Orrery",
  "Rune-Forged Blade", "Shadow Dagger", "Ethereal Armor Set", "Aegis of the Fallen", "Helm of Command",
  "Boots of Swiftness", "Cloak of Invisibility", "Gauntlets of Might", "Ring of Evocation", "Amulet of Vitality",
  "Crown of Kings", "Staff of Elements", "Shield of Valor", "Warhammer of Titan", "Bow of the Hunter",
  "Gilded Chalice", "Tome of Ancients", "Mirror of Truth", "Orb of Sight", "Lantern of Souls",
  "Scepter of Power", "Horn of Plenty", "Altar of Devotion", "Pedestal of Glory", "Vault of Secrets",
  "Scroll of Wisdom", "Compass of the Lost", "Hourglass of Time", "Chime of Harmony", "Censer of Peace",
  "Darksteel Forge Node", "Mind Stone Matrix", "Hedron Network Fragment", "Thought Vessel Core", "Reliquary Tower Key",
  "Sol Ring Replica", "Thran Dynamo Catalyst", "Gilded Lotus Blossom", "Lotus Petal Shard", "Black Lotus Fragment",
  "Mana Vault Lock", "Grim Monolith Pillar", "Basalt Monolith Fragment", "Mox Diamond Prism", "Mox Opal Shard",
  "Mox Amber Gem", "Chrome Mox Plating", "Mox Tantalite Catalyst", "Jeweled Lotus Petal", "Mana Crypt Key",
  "Lightning Greaves Set", "Swiftfoot Boots Pair", "Champion's Helm Core", "Skullclamp Fixture", "Ashnod's Altar Base",
  "Phyrexian Altar Frame", "Nim Deathmantle Weave", "Aetherflux Reservoir Core", "Bolas's Citadel Gate", "Sensei's Divining Top Node",
  "Smothering Tithe Ledger", "Esper Sentinel Shield", "Rhystic Study Tome", "Mystic Remora Shell", "Sylvan Library Scroll",
  "Necropotence Skull", "Phyrexian Arena Floor", "Black Market Connections Node", "Kindred Discovery Rune", "Guardian Project Grove",
  "Beast Whisperer Companion", "Lifecrafter's Bestiary Page", "Great Henge Root", "Trouble in Pairs Seal", "Monologue Tax Ledger",
  "Loran's Third Path Relic", "Skyclave Apparition Spirit", "Solitude Essence", "Grief Whispers", "Subtlety Shard",
  "Endurance Roots", "Fury Flames", "Force of Will Scroll", "Force of Negation Shield", "Mana Drain Catalyst",
  "Counterspell Wand", "Fierce Guardianship Ward", "Deflecting Swat Spark", "Deadly Rollick Dagger", "Flawless Maneuver Crest",
  "Heroic Intervention Charm", "Teferi's Protection Veil", "Cyclonic Rift Vortex", "Toxic Deluge Vial", "Damnation Orb",
  "Wrath of God Tablet", "Blasphemous Act Rune", "Vanquish the Horde Blade", "Farewell Light", "Supreme Verdict Gavel",
  "Languish Smoke", "Crux of Fate Dragon Scale", "Extinction Event Marker", "Shadows' Verdict Mask", "Crippling Fear Shackles",
  "Meathook Massacre Wire", "Bastion of Remembrance Flag", "Dreadhorde Invasion Banner", "Bitterblossom Petal", "Skrelv's Hive Node",
  "Ghoulcaller's Tome", "Poppet Stitcher Needle", "Ophiomancer Idol", "Grave Titan Chain", "Wurmcoil Core",
  "Noxious Gearhulk Visage", "Verdurous Gearhulk Moss", "Combustible Gearhulk Ash", "Torrential Gearhulk Wave", "Cataclysmic Gearhulk Crest",
  "Sword of Feast and Famine", "Sword of Fire and Ice", "Sword of Light and Shadow", "Sword of Body and Mind", "Sword of War and Peace",
  "Sword of Truth and Justice", "Sword of Sinew and Steel", "Sword of Hearth and Home", "Sword of Forge and Frontier", "Sword of Once and Future",
  "Shadowspear Point", "Umezawa's Jitte Edge", "Batter-skull Assembly", "Kaldra Compleat Relic", "Hammer of Nazahn", "Colossus Hammer Heavy",
  "Bloodforged Battle-Axe", "Blackblade Reforged", "Mace of the Valiant", "Sword of the Animist", "Heirloom Blade",
  "Hero's Blade", "Infiltration Lens", "Mask of Memory", "Skullclamp Wire", "Loxodon Warhammer",
  "Quietus Spike", "Scythe of the Wretched", "Argentum Armor", "Fireshrieker", "Grafted Exoskeleton",
  "Whispersilk Cloak", "Swiftfoot Boots", "Lightning Greaves", "Prowler's Helm", "Rogue's Gloves",
  "Trailblazer's Boots", "Zephyr Boots", "Fleetfeather Sandals", "Winged Boots", "Strider Harness",
  "Darksteel Plate", "Shield of Kaldra", "Sword of Kaldra", "Helm of Kaldra", "Ring of Kalonia",
  "Ring of Evos Isle", "Ring of Xathrid", "Ring of Valkas", "Ring of Thune", "Mirran Spyglass",
  "Spyglass of the Seekers", "Glasses of Urza", "Urza's Bauble", "Mishra's Bauble", "Conjurer's Bauble",
  "Wayfarer's Bauble", "Soul-Guide Lantern", "Relic of Progenitus", "Tormod's Crypt", "Nihil Spellbomb",
  "Scrabbling Claws", "Phyrexian Spellbomb", "Sunbeam Spellbomb", "Lifespark Spellbomb", "Aether Spellbomb",
  "Flight Spellbomb", "Necrogen Spellbomb", "Pyrite Spellbomb", "Origin Spellbomb", "Panic Spellbomb"
  // PART 4 OF 4: NON-BASIC & BASIC LANDS, FINAL UTILITY & CLOSING ARRAY (Cards 901 to 1,157)
  "Bojuka Bog", "Takenuma, Abandoned Mire", "Boseiju, Who Endures", "Eiganjo, Seat of the Empire", "Otawara, Soaring City",
  "Sokenzan, Crucible of Defiance", "Reliquary Tower", "Rogue's Passage", "High Market", "Phyrexian Tower",
  "Westvale Abbey", "Volrath's Stronghold", "Academy Ruins", "Hall of Heliod's Generosity", "Field of the Dead",
  "Scavenger Grounds", "Geier Reach Sanitarium", "Mikokoro, Center of the Sea", "War Room", "Bonders' Enclave",
  "Castle Locthwain", "Castle Garenbrig", "Castle Vantress", "Castle Ardenvale", "Castle Embereth",
  "Witch's Cottage", "Gingerbread Cabin", "Idyllic Grange", "Dwarf Hold", "Hickory Woodlot",
  "Peat Bog", "Remote Farm", "Sandstone Needle", "Saprazzan Skerry", "Ebon Stronghold",
  "Havenwood Battleground", "Ruins of Trokair", "Svyelunite Temple", "Dwarven Ruins", "Vault of Champions",
  "Spectator Seating", "Training Center", "Undergrowth Stadium", "Rejuvenating Springs", "Vault of Whispers",
  "Tree of Tales", "Seat of the Synod", "Great Furnace", "Ancient Den", "Darksteel Citadel",
  "Arcane Lighthouse", "Detection Tower", "Homeward Path", "Command Beacon", "Spire of Industry",
  "Aether Hub", "Exotic Orchard", "Path of Ancestry", "Reflecting Pool", "City of Brass",
  "Mana Confluence", "Forbidden Orchard", "Tarnished Citadel", "Gemstone Mine", "Crystal Quarry",
  "Cascading Cataracts", "Shimmering Grotto", "Unknown Shores", "Holdout Settlement", "Survivors' Encampment",
  "Cryptic Caves", "Arch of Orazca", "Estate Gate", "Cliffgate", "Black Dragon Gate",
  "Citadel Gate", "Sea Gate", "Gond Gate", "Heap Gate", "Manor Gate",
  "Baldur's Gate", "Thran Portal", "Demolition Field", "Field of Ruin", "Ghost Quarter",
  "Tectonic Edge", "Encroaching Wastes", "Wasteland", "Strip Mine", "Dust Bowl", "Deserted Temple",
  "Nykthos, Shrine to Nyx", "Cabal Coffers", "Cabal Stronghold", "Urborg, Tomb of Yawgmoth", "Yavimaya, Cradle of Growth",
  "Crypt of Agadeem", "Lake of the Dead", "Phyrexian Devourer Land", "Volcano Hellion Ridge", "Glacial Chasm",
  "Maze of Ith", "Kor Haven", "Prahv, Spires of Order", "Sunhome, Fortress of the Legion", "Skarrg, the Rage Pits",
  "Vitu-Ghazi, the City-Tree", "Svogthos, the Restless Tomb", "Duskmantle, House of Shadow", "Nivix, Aerie of the Firemind", "Orzhova, the Church of Deals",
  "Rath's Edge", "Kor Haven Garrison", "Kessig Wolf Run", "Gavony Township", "Moorland Haunt",
  "Nephalia Drownyard", "Vault of the Archangel", "Alchemist's Refuge", "Slayer's Stronghold", "Desolate Lighthouse",
  "Grim Backwoods", "Rogue's Hideout", "Spawning Bed", "Foundry of the Consuls", "Gargoyle Castle",
  "Mage-Ring Network", "Dread Statuary", "Stirring Wildwood", "Raging Ravine", "Lumbering Falls",
  "Celestial Colonnade", "Creeping Tar Pit", "Hissing Quagmire", "Needleverge Pathway", "Hengegate Pathway",
  "Branchloft Pathway", "Brightclimb Pathway", "Clearwater Pathway", "Cragcrown Pathway", "Darkbore Pathway",
  "Riverglide Pathway", "Barkchannel Pathway", "Blightstep Pathway", "Kaldheim Snow Swamp", "Kaldheim Snow Forest",
  "Kaldheim Snow Plains", "Kaldheim Snow Mountain", "Kaldheim Snow Island", "Ash Barrens", "Evolving Wilds Core",
  "Terramorphic Expanse Core", "Myriad Landscape", "Bighted Woodland", "Blighted Fen", "Blighted Cataract",
  "Blighted Gorge", "Blighted Steppe", "Haunted Mire", "Idyllic Beachfront", "Radiant Grove",
  "Sunlit Marsh", "Tangling Islet", "Wooded Ridgeline", "Contaminated Aquifer", "Geothermal Bog",
  "Molten Tributary", "Sacred Peaks", "Overgrown Farmland", "Deserted Beach", "Haunted Ridge",
  "Rockfall Vale", "Shipwreck Marsh", "Dreamroot Cascade", "Shattered Sanctum", "Stormcarved Coast",
  "Sundown Pass", "Deathcap Glade", "Restless Bivouac", "Restless Fortress", "Restless Cottage",
  "Restless Spire", "Restless Reef", "Restless Vents", "Restless Anchorage", "Restless Prairie",
  "Restless Ridge", "Restless Marsh", "Llanowar Reaches", "Sylvan Basin", "Gloom Mire",
  "Sunstone Quarry", "Frost peak Summit", "Windswept Crag", "Volcanic Ridge", "Ethereal Valley",
  "Obsidian Crater", "Chrono Spring", "Void Abyss", "Titan's Graveyard", "Crystal Cavern",
  "Swamp", "Forest", "Plains", "Mountain", "Island"
];
